name: CI/CD Pipeline

on:
  push:
    branches: [ "pipeline-test" ]
  pull_request:
    branches: [ "pipeline-test" ]

jobs:
  Debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test

      - name: Printing test
        run: |
          echo "Github Event Description"
          echo ${{ github.event.description }}
          echo "Github Event Push"
          echo ${{ github.event.push }}
          echo "ENTIRE CONTEXT"
          echo ${{ toJSON(github) }}
          echo "Done"


  Linting:
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Perform linting
        run: bundle exec rubocop

  Test:
    if: ${{ false }}
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      
      - name: Build test database
        run: |
          bundle exec rake db:migrate
          bundle exec rake db:seed
      
      - name: Run spec tests
        run: bundle exec rspec
      
      - name: Run feature tests
        run: bundle exec cucumber
    
  Production:
    if: ${{ false }}
    needs: Test

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production

    steps:
      - name: Prod placeholder
        run: echo "Replace me with a real step!"
  
  Deploy:
    if: ${{ false }}
    needs: Production

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production

    steps:
      - name: Deploy placeholder
        run: echo "Write steps to deploy to Heroku!"
