name: CI/CD Pipeline

on:
  push:
    branches: [ "pipeline-test" ]
  pull_request:
    branches: [ "pipeline-test" ]

jobs:
  Debug:
    runs-on: ubuntu-latest

    outputs:
      date: ${{ steps.get-date.outputs.date }}
      mappings: ${{ steps.get-mappings.outputs.mappings }}

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test
      
      - name: Export current date
        id: get-date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
      
      - name: Export Heroku mappings
        id: get-mappings
        run: |
          export mappings=$(cat .github/workflows/heroku-mappings.json)

      - name: Read mappings
        run: echo ${{ $mappings }}
          


  Linting:
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Perform linting
        run: bundle exec rubocop

  Test:
    if: ${{ false }}
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test
      
      - name: Set up Ruby 2.6.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      
      - name: Build test database
        run: |
          bundle exec rake db:migrate
          bundle exec rake db:seed
      
      - name: Run spec tests
        run: bundle exec rspec
      
      - name: Run feature tests
        run: bundle exec cucumber
    
  Production:
    needs: Test

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Set up Ruby 2.6.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: false
      
      - name: Build production database
        run: |
          bundle exec rake db:migrate
          bundle exec rake db:seed
      
      - name: Run spec tests
        run: bundle exec rspec
      
      - name: Run feature tests
        run: bundle exec cucumber
  
  Deploy:
    needs: Production

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production

    steps:
      - name: Deploy placeholder
        run: echo "Write steps to deploy to Heroku!"
