name: CI/CD Pipeline

on:
  push:
    branches: [ "pipeline-test" ]
  pull_request:
    branches: [ "pipeline-test" ]

jobs:
  Debug:
    runs-on: ubuntu-latest

    outputs:
      date: ${{ steps.date.outputs.date }}
      mappings: ${{ steps.mappings.outputs.mappings }}
      heroku-app: $ {{ steps.app-name.outputs.name }}

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test
      
      - name: Export current date
        id: date
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      
      - name: Export Heroku mappings
        id: mappings
        run: |
          echo "mappings=$(cat .github/workflows/heroku-mappings.json)" >> $GITHUB_OUTPUT
      
      # 2022-11-01 <= current_date <= 2022-11-09
      - if: (fromJson(steps.date.outputs.date) >= fromJson(steps.mappings.outputs.mappings).sprint1_start) && (fromJson(steps.date.outputs.date) <= fromJson(steps.mappings.outputs.mappings).sprint2_start)
        run: |
          echo "WE'RE IN SPRINT 1"
          echo "HEROKU_APP=$($HEROKU_APP)" >> $GITHUB_ENV
        env:
          HEROKU_APP: ${{ fromJson(steps.mappings.outputs.mappings).sprint1_app_name }}
      
      # 2022-11-10 <= current_date <= 2022-11-27
      - if: (fromJson(steps.date.outputs.date) >= fromJson(steps.mappings.outputs.mappings).sprint2_start) && (fromJson(steps.date.outputs.date) <= fromJson(steps.mappings.outputs.mappings).sprint3_start)
        run: |
          echo "WE'RE IN SPRINT 2"
          echo "HEROKU_APP=$($HEROKU_APP)" >> $GITHUB_ENV
        env:
          HEROKU_APP: ${{ fromJson(steps.mappings.outputs.mappings).sprint2_app_name }}

      # 2022-11-28 <= current_date
      - if: fromJson(steps.date.outputs.date) >= fromJson(steps.mappings.outputs.mappings).sprint3_start
        run: |
          echo "SPRINT 3"
          echo "HEROKU_APP=$($HEROKU_APP)" >> $GITHUB_ENV
        env:
          HEROKU_APP: ${{ fromJson(steps.mappings.outputs.mappings).sprint3_app_name }}
      
      - name: View Heroku app name
        run: | 
          echo "HEROKU APP NAME IS"
          echo ${{ env.HEROKU_APP }}
        


  Linting:
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Perform linting
        run: bundle exec rubocop

  Test:
    if: ${{ false }}
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout pipeline-test
        uses: actions/checkout@v3
        with:
          ref: pipeline-test
      
      - name: Set up Ruby 2.6.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      
      - name: Build test database
        run: |
          bundle exec rake db:migrate
          bundle exec rake db:seed
      
      - name: Run spec tests
        run: bundle exec rspec
      
      - name: Run feature tests
        run: bundle exec cucumber
    
  Production:
    needs: Test

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Set up Ruby 2.6.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: false
      
      - name: Build production database
        run: |
          bundle exec rake db:migrate
          bundle exec rake db:seed
      
      - name: Run spec tests
        run: bundle exec rspec
      
      - name: Run feature tests
        run: bundle exec cucumber
  
  Deploy:
    needs: Production

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production

    steps:
      - name: Deploy placeholder
        run: echo "Write steps to deploy to Heroku!"
